# Generated by Django 5.1.2 on 2024-10-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(max_length=10, null=True, unique=True)),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('estado_categoria', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(blank=True, max_length=50)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('estado_producto', models.BooleanField(default=True)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
            options={
                'unique_together': {('categoria_producto', 'codigo_interno')},
            },
        ),
    ]
